products:
- id: 151
  name: "Samsung Galaxy S25 Plus , 512GB, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Navy, Silver Shadow, Mint , Icy Blue. The Samsung Galaxy
    S25+ (released Feb 2025) is a high-end Android smartphone featuring a 6.7-inch
    QHD+ 120Hz AMOLED display, the Snapdragon 8 Elite processor, and 12GB of RAM. It
    includes a 4,900 mAh battery with 45W charging, a triple rear camera system
    (50MP main), and AI features within One UI 7. Key Specifications:

- id: 152
  name: "Samsung Galaxy S26 Plus, 256GB, Unlocked, New, Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Skyblue , Black , White, Cobalt Violet . The Samsung Galaxy
    S26+ (released March 2026) is a high-end AI-focused smartphone featuring a
    6.7-inch 120Hz QHD+ AMOLED display, Snapdragon 8 Elite Gen 5 chipset, and 12GB
    of RAM. Key specs include a 4900mAh battery, 45W wired charging, 50MP triple
    cameras, and Android 16 with heavy Galaxy AI integration, available in 256GB or
    512GB. Key Specifications of the Samsung Galaxy S26+:

- id: 153
  name: "Samsung Galaxy S26 Ultra , 1TB, Unlocked, New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors White, Black, Skyblue, Cobalt Violet. The Samsung Galaxy S26
    Ultra (released early 2026) features a 6.9-inch QHD+ 120Hz display with
    integrated privacy technology, powered by the Snapdragon 8 Elite Gen 5 chip. It
    boasts a 200MP main camera with improved aperture, a 50MP 5x periscope lens, 60W
    wired charging, and a 5,000 mAh battery, all in a thinner 214g Armor Aluminum
    body. Key Specifications

- id: 154
  name: "Samsung Galaxy S26 Plus , 512GB, Unlocked, New, Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Skyblue , Black , white , Cobalt Violet. The Samsung Galaxy
    S26+ (released March 2026) is a high-end AI-focused smartphone featuring a
    6.7-inch 120Hz QHD+ AMOLED display, Snapdragon 8 Elite Gen 5 chipset, and 12GB
    of RAM. Key specs include a 4900mAh battery, 45W wired charging, 50MP triple
    cameras, and Android 16 with heavy Galaxy AI integration, available in 256GB or
    512GB. Key Specifications of the Samsung Galaxy S26+:

- id: 155
  name: "Samsung Galaxy S26, 512GB, Unlocked, New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Black , White , Skyblue Cobalt Violet. Released in March
    2026, the Samsung Galaxy S26 series (S26, S26+, S26 Ultra) features the
    Snapdragon 8 Elite Gen 5 for Galaxy (or Exynos 2600), Android 16, and advanced
    Galaxy AI. The S26 Ultra features a 200MP camera, 50MP 10x telephoto lens,
    5,000mAh battery, and a unique, built-in \"Privacy Display\". Key Specifications
    & Features (S26 Ultra Focus):

- id: 156
  name: "Samsung Galaxy S26 Ultra, 512GB, Unlocked ,New , Sealed Sale"
  category: "Phones"
  description: >-
    >- Available Colors Black, White, Skyblue, Cobalt Violet. The Samsung Galaxy S26
    Ultra (released early 2026) features a 6.9-inch QHD+ 120Hz display with
    integrated privacy technology, powered by the Snapdragon 8 Elite Gen 5 chip. It
    boasts a 200MP main camera with improved aperture, a 50MP 5x periscope lens, 60W
    wired charging, and a 5,000 mAh battery, all in a thinner 214g Armor Aluminum
    body. Key Specifications

- id: 157
  name: "Samsung Galaxy S26 Ultra  256GB, Unlocked"
  category: "Phones"
  description: >-
    >- Available White, Black, Skyblue, Cobalt Violet, The Samsung Galaxy S26 Ultra
    (released early 2026) features a 6.9-inch QHD+ 120Hz display with integrated
    privacy technology, powered by the Snapdragon 8 Elite Gen 5 chip. It boasts a
    200MP main camera with improved aperture, a 50MP 5x periscope lens, 60W wired
    charging, and a 5,000 mAh battery, all in a thinner 214g Armor Aluminum body.
    Key Specifications

- id: 158
  name: "Samsung Galaxy S26, 256GB, Unlocked, New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Black , White, Sky Blue , Cobalt Violet . Released in March
    2026, the Samsung Galaxy S26 series (S26, S26+, S26 Ultra) features the
    Snapdragon 8 Elite Gen 5 for Galaxy (or Exynos 2600), Android 16, and advanced
    Galaxy AI. The S26 Ultra features a 200MP camera, 50MP 10x telephoto lens,
    5,000mAh battery, and a unique, built-in \"Privacy Display\". Key Specifications
    & Features (S26 Ultra Focus):

- id: 159
  name: "Samsung Galaxy F17, 128GB, Latin Spec, Unlocked, New, Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Black. The Samsung Galaxy F17 5G (4GB/128GB) features a
    6.7-inch FHD+ Super AMOLED 90Hz display, Exynos 1330 chipset, and a 5000mAh
    battery with 25W charging. It includes a 50MP OIS main camera, 5MP ultrawide
    lens, and 13MP front camera, running Android 15 with 6 years of software
    support. It is 7.5mm thick with 5G, 4GB RAM, and 128GB storage. Key
    Specifications

- id: 160
  name: "Samsung Galaxy A17, 8GB, 256GB, Latin Spec, Unlocked, New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Black, Blue. The Samsung Galaxy A17 5G (released early 2026)
    is a budget-focused smartphone featuring a 6.7-inch 90Hz FHD+ Super AMOLED
    display, an Exynos 1330 processor, and a 5,000 mAh battery with 25W charging. It
    offers a 50MP main camera with OIS, 4GB/6GB/8GB RAM, and 128GB/256GB storage.
    Key Specifications:

- id: 161
  name: "Samsung Galaxy A17, 6GB, 128GB, Latin Spec, Unlocked, New , Sealed."
  category: "Phones"
  description: >-
    >- Available Colors Black, Blue. The Samsung Galaxy A17 5G (released early 2026)
    is a budget-focused smartphone featuring a 6.7-inch 90Hz FHD+ Super AMOLED
    display, an Exynos 1330 processor, and a 5,000 mAh battery with 25W charging. It
    offers a 50MP main camera with OIS, 4GB/6GB RAM, and 128GB/256GB storage. Key
    Specifications:

- id: 162
  name: "Samsung Galaxy A07, 128GB, Latin Spec , Unlocked ,New ,Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Black , Green. The Samsung Galaxy A07 (2026) is a
    budget-friendly smartphone featuring a 6.7-inch 90Hz/120Hz PLS LCD display, a
    50MP main camera, and a 5,000–6,000 mAh battery with 25W charging. Available in
    4G (Helio G99) and 5G (Dimensity 6300) variants, it offers 4GB-8GB RAM,
    128GB-256GB storage, and runs Android 16. Key Specifications:

- id: 163
  name: "Samsung Galaxy A05, 128GB, Latin Spec, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Black, Green , Silver. The Samsung Galaxy A05 is a
    budget-friendly 4G smartphone featuring a large 6.7-inch HD+ PLS LCD display, a
    50MP main rear camera, and a 5,000mAh battery with 25W fast charging support.
    Powered by the MediaTek Helio G85 chipset with 4GB/6GB RAM, it offers basic
    performance suitable for daily tasks, running on Android 13/14. Key
    Specifications:

- id: 164
  name: "Samsung Galaxy A06, 64GB, Latin Spec, Unlocked , New, Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Black. The Samsung Galaxy A06 is an budget-friendly 4G LTE
    smartphone (2024) featuring a 6.7-inch HD+ display, 50MP main camera, and
    5,000mAh battery. It runs Android 14 with a MediaTek Helio G85 processor,
    available in 64GB/128GB storage options, and includes a side fingerprint sensor.
    This unlocked, black model is ideal for basic tasks. Key Features &
    Specifications:

- id: 165
  name: "Samsung Galaxy A06, 128GB, Latin Spec, Unlocked , New, Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Black. The Samsung Galaxy A06 is an budget-friendly 4G LTE
    smartphone (2024) featuring a 6.7-inch HD+ display, 50MP main camera, and
    5,000mAh battery. It runs Android 14 with a MediaTek Helio G85 processor,
    available in 64GB/128GB storage options, and includes a side fingerprint sensor.
    This unlocked, black model is ideal for basic tasks. Key Features &
    Specifications:

- id: 166
  name: "Samsung Galaxy Z Fold 7, 512GB, Latin Spec, Unlocked, New, Sealed"
  category: "Phones"
  description: >-
    >+ Available Colors Black , Shadow Blue, Silver Shadow The Samsung Galaxy Z
    Fold7 (released 2026) is a high-end foldable featuring a 200MP main camera,
    Snapdragon 8 Elite chip, and up to 16GB RAM, starting at roughly $1,599. It
    offers an 8-inch main display and a 6.5-inch cover screen, boasting a 215g
    weight, IP48 rating, and 7 years of software support. Core Specifications

- id: 167
  name: "Samsung Galaxy Z Fold 7, 256GB, Latin Spec, Unlocked, New, Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Black , Blue Shadow , Silver Shadow The Samsung Galaxy Z
    Fold 7 (released 2026) is a high-end foldable featuring a 200MP main camera,
    Snapdragon 8 Elite chip, and up to 16GB RAM, starting at roughly $1999 It offers
    an 8-inch main display and a 6.5-inch cover screen, boasting a 215g weight, IP48
    rating, and 7 years of software support. Core Specifications

- id: 168
  name: "Samang Galaxy Z Flip 7 FE, 256GB, Latin Spec, Unlocked, New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Black & White The Samsung Galaxy Z Flip 7 FE (released July
    2025) is a mid-range foldable priced around featuring a 6.7-inch 120Hz LTPO main
    display, 3.4-inch 60Hz cover screen, and an Exynos 2400 processor. It includes
    8GB RAM, 128/256GB storage, a 4,000mAh battery, 50MP main camera, and Android
    16. Key Specifications (Based on 2025 Reports):

- id: 169
  name: "Samsung Galaxy Z Fold 7, 1TB , Latin Spec, Unlocked, New, Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Black , Blue Shadow , Silver Shadow The Samsung Galaxy Z
    Fold 7 (released 2026) is a high-end foldable featuring a 200MP main camera,
    Snapdragon 8 Elite chip, and up to 16GB RAM, starting at roughly $1,599. It
    offers an 8-inch main display and a 6.5-inch cover screen, boasting a 215g
    weight, IP48 rating, and 7 years of software support. Core Specifications

- id: 170
  name: "Samang Galaxy Z Flip 7 FE, 128GB, Latin Spec, Unlocked, New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Black & White The Samsung Galaxy Z Flip 7 FE (released July
    2025) is a mid-range foldable priced around featuring a 6.7-inch 120Hz LTPO main
    display, 3.4-inch 60Hz cover screen, and an Exynos 2400 processor. It includes
    8GB RAM, 128/256GB storage, a 4,000mAh battery, 50MP main camera, and Android
    16. Key Specifications (Based on 2025 Reports):

- id: 171
  name: "Samsung Galaxy Z Flip 7 , 256GB , Latin Spec, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Jet Black, Coral Red , Blue Shadow . The Samsung Galaxy Z
    Flip 7 (released July 2025) features a 6.9-inch 120Hz LTPO main display, a
    larger 4.1-inch 120Hz cover screen, and is powered by the Exynos 2500 chipset
    with 12GB of RAM. It includes a 50MP main camera, a 4,300mAh battery, 25W
    charging, and runs Android 16. Core Specifications: Main Display: 6.9-inch
    Dynamic AMOLED 2X, 120Hz, FHD+ resolution, foldable Ultra Thin Glass. Cover
    Display: 4.1-inch, 120Hz, 2400 nits peak brightness, enhanced \"Flex Window\".

- id: 172
  name: "Samsung Galaxy Z Flip 7 , 512GB , Latin Spec, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Jet Black, Coral Red , Blue Shadow . The Samsung Galaxy Z
    Flip 7 (released July 2025) features a 6.9-inch 120Hz LTPO main display, a
    larger 4.1-inch 120Hz cover screen, and is powered by the Exynos 2500 chipset
    with 12GB of RAM. It includes a 50MP main camera, a 4,300mAh battery, 25W
    charging, and runs Android 16. Core Specifications: Main Display: 6.9-inch
    Dynamic AMOLED 2X, 120Hz, FHD+ resolution, foldable Ultra Thin Glass. Cover
    Display: 4.1-inch, 120Hz, 2400 nits peak brightness, enhanced \"Flex Window\".

- id: 173
  name: "Samsung Galaxy A26, 256GB, Latin Spec , Unlocked , New , Sealed Sale"
  category: "Phones"
  description: >-
    >- Available Colors Pink, Black, White , Mint . The Samsung Galaxy A26 5G (2025)
    is a mid-range device featuring a 6.7-inch 120Hz FHD+ Super AMOLED display,
    powered by an Exynos 1380 chipset, up to 8GB of RAM, and 256GB of storage. It
    boasts a 50MP OIS main camera, 13MP selfie camera, a 5,000mAh battery with 25W
    charging, and IP67 water resistance, running Android 15 with 6 years of promised
    updates. Key Specifications:

- id: 174
  name: "Samsung Galaxy A26, 128GB, Latin Spec , Unlocked , New , Sealed"
  category: "Phones"
  description: ""

- id: 175
  name: "Samsung Galaxy A56, 256GB, Latin Spec , Unlocked , New, Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Awesome Graphite, Awesome Light Gray, Awesome Olive, Awesome
    Pink. The Samsung Galaxy A56 5G (released March 2025) is a mid-range phone
    featuring a 6.7-inch 120Hz Super AMOLED display, Exynos 1580 chipset, and
    8GB/12GB RAM. Key specs include a 50MP main camera with 4K video, 5,000mAh
    battery, 45W fast charging, and IP67 water resistance, all protected by Gorilla
    Glass Victus+. Key Specifications:

- id: 176
  name: "Samsung Galaxy A56, 128GB, Latin Spec , Unlocked , New, Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Awesome Graphite, Awesome Light Gray, Awesome Olive, Awesome
    Pink. The Samsung Galaxy A56 5G (released March 2025) is a mid-range phone
    featuring a 6.7-inch 120Hz Super AMOLED display, Exynos 1580 chipset, and
    8GB/12GB RAM. Key specs include a 50MP main camera with 4K video, 5,000mAh
    battery, 45W fast charging, and IP67 water resistance, all protected by Gorilla
    Glass Victus+. Key Specifications:

- id: 177
  name: "Samsung Galaxy A36, 256GB, Latin Spec , Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >+ Available Colors Awesome Lime , Awesome Black, Awesome Lavender, Awesome
    White. The Samsung Galaxy A36 5G is a 2025 mid-range smartphone featuring a
    6.7-inch 120Hz FHD+ Super AMOLED display (up to 1900 nits) and a 50MP main
    camera. It is powered by a Qualcomm Snapdragon 6 Gen 3 processor, a 5000mAh
    battery with 45W fast charging, and runs Android 15 with 6 years of security
    support. Key Specifications:

- id: 178
  name: "Samsung Galaxy A16 , 128GB , 4G, Latin Spec , Unlocked, New ,Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Blue Black, Light Gray, Light Green, Gold. The Samsung
    Galaxy A16 is a budget-friendly 5G smartphone featuring a 6.7-inch FHD+ Super
    AMOLED 90Hz display, 50MP triple cameras, and a 5,000mAh battery with 25W
    charging. It runs on an Exynos 1330 (5nm) chipset with 4GB/8GB RAM, up to 256GB
    expandable storage, and offers an impressive 6 years of software support. Key
    Specifications

- id: 179
  name: "Samsung Galaxy A36, 128GB, Latin Spec , Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Awesome Lime , Awesome Black, Awesome Lavender, Awesome
    White. The Samsung Galaxy A36 5G is a 2025 mid-range smartphone featuring a
    6.7-inch 120Hz FHD+ Super AMOLED display (up to 1900 nits) and a 50MP main
    camera. It is powered by a Qualcomm Snapdragon 6 Gen 3 processor, a 5000mAh
    battery with 45W fast charging, and runs Android 15 with 6 years of security
    support. Key Specifications:

- id: 180
  name: "Samsung Galaxy A16 , 256GB , 4G, Latin Spec , Unlocked, New ,Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Blue Black, Light Gray, Light Green, Gold. The Samsung
    Galaxy A16 is a budget-friendly 5G smartphone featuring a 6.7-inch FHD+ Super
    AMOLED 90Hz display, 50MP triple cameras, and a 5,000mAh battery with 25W
    charging. It runs on an Exynos 1330 (5nm) chipset with 4GB/8GB RAM, up to 256GB
    expandable storage, and offers an impressive 6 years of software support. Key
    Specifications

