products:
- id: 181
  name: "Samsung Galaxy M55, 256GB, Latin Spec, Unlocked , New, Sealed"
  category: "Phones"
  description: >-
    >- The Samsung Galaxy M55 5G is a slim (7.8mm) smartphone featuring a 6.7-inch
    FHD+ 120Hz Super AMOLED Plus display, a Qualcomm Snapdragon 7 Gen 1 processor,
    and 8GB/12GB RAM. It boasts a 50MP primary camera with OIS and a 50MP front
    camera, backed by a 5,000mAh battery with 45W fast charging. Key Specifications:

- id: 182
  name: "Samsung Galaxy S24 FE, 256GB , Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Gay Graphite The Samsung Galaxy S24 FE is a
    high-performance, fan-edition smartphone featuring a 6.7-inch Dynamic AMOLED 2X
    display, 120Hz refresh rate, and 1,900 nits peak brightness. It is powered by
    the Exynos 2400e processor, 8GB RAM, a 4,700 mAh battery, and includes a 50MP
    main camera. It runs Android 14, supports 25W charging, and has an IP68 rating.
    Core Specifications

- id: 183
  name: "Samsung Galaxy A54, 128GB,  Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Black , Violet. The Samsung Galaxy A54 5G is a mid-range
    smartphone featuring a 6.4-inch 120Hz Super AMOLED display, a 50MP main camera
    with OIS, and a 5,000mAh battery. Powered by the Exynos 1380 processor, it
    offers 6GB/8GB RAM and 128GB/256GB storage (expandable). It is known for its
    durable design, IP67 rating, and reliable battery life. Key Specgifications

- id: 185
  name: "Meizu Note 21, 256GB,  GSM Unlocked , International Version, New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Blue. The Meizu 21 Note (256GB storage) is a high-performance
    5G smartphone featuring the Snapdragon 8 Gen 2 chipset, a 6.78-inch 144Hz LTPO
    AMOLED display, and 16GB LPDDR5 RAM. It packs a 5500mAh battery with 66W fast
    charging, a 50MP main camera, and operates on Android 14 based on Flyme 10.5,
    emphasizing AI capabilities. Key Specifications of the Meizu 21 Note (256GB
    model):

- id: 186
  name: "Honor X8A, 256GB,  GSM Unlocked , International Version , New ,Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Blue. The Honor X8a is a 4G budget smartphone featuring a
    6.7-inch 90Hz LCD, a 100MP main camera, and a slim 7.48mm design. Powered by a
    MediaTek Helio G88 processor with 8GB RAM and 128GB storage, it includes a
    4500mAh battery with 22.5W fast charging and runs on MagicUI 6.1 (Android 12).
    Key Specifications of the Honor X8a:

- id: 187
  name: "ZTE Nubia Music, 128GB, 4G ,GSM Unlocked , International Version , New,"
  category: "Phones"
  description: >-
    >- (This Smartphone Is Compatible With Only T-Mobile , Mint Mobile , Metro by
    T-Mobile, Tello Mobile, Ultra Mobile In The US) ZTE smartphones are highly
    compatible with carriers in Africa, the Middle East, Asia, the Caribbean, Latin
    America ,UK and Europe. You will get high-speed data and voice service in US
    cities, but expect dropped signals or roaming issues in rural areas in the US
    due to a lack of low-frequency bands .Avaiable Colors Pop Art , Orange The Nubia
    Music is a budget-focused smartphone (typically 4G/LTE, not 5G) designed for
    audio enthusiasts, featuring a high-volume \"vinyl-record\" style speaker, dual
    3.5mm headphone jacks, and a 5000mAh battery. It offers 128GB storage, a 50MP
    camera, and a 90Hz display, but provides modest performance using a Unisoc T606
    processor. Key Features and Details Audio Focus: The rear speaker is 600% louder
    than standard phones and features melodic light effects that sync with music. It
    includes DTS:X® Ultra for sound enhancement. Unique Design: Available in vibrant
    \"Pop Art\" colors and an orange variant, designed to look like a, portable
    radio. Dual Headphone Jacks: Allows two people to listen to the same device
    simultaneously via wired headphones.

- id: 188
  name: "Samsung Galaxy S24, 256GB, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Orange, Yellow, Gray , Black , Violet. The Samsung Galaxy S24
    features a 6.2-inch FHD+ 120Hz Dynamic AMOLED 2X display, Snapdragon 8 Gen 3 for
    Galaxy chipset (or Exynos 2400 depending on region), 8GB RAM, and a 4,000mAh
    battery. It offers 50MP main, 12MP ultra-wide, and 10MP telephoto (3x zoom)
    cameras, plus 128GB/256GB/512GB storage options and 7 years of security updates.
    Key Specifications for Galaxy S24:

- id: 189
  name: "ZTE Nubia Neo 2, 256GB ,GSM Unlocked , International Version , New , Sealed"
  category: "Phones"
  description: >-
    >- (This Smartphone Is Compatible With Only T-Mobile , Mint Mobile , Metro by
    T-Mobile, Tello Mobile, Ultra Mobile In The US) ZTE smartphones are highly
    compatible with carriers in Africa, the Middle East, Asia, the Caribbean, Latin
    America,UK and Europe. You will get high-speed data and voice service in US
    cities, but expect dropped signals or roaming issues in rural areas in the US
    due to a lack of low-frequency bands. The ZTE Nubia Neo 2 5G is a budget gaming
    smartphone featuring a 6.72-inch 120Hz FHD+ display, a Unisoc T820 processor,
    and dual gaming shoulder triggers. It packs a 6000mAh battery with 33W fast
    charging, 8GB RAM (expandable), and 256GB storage, all within a mecha-design
    body, often running Android 14. Key Specifications:

- id: 190
  name: "Xiaomi Poco C75, 128GB , GSM Unlocked , International Version , New ,"
  category: "Phones"
  description: >-
    >- (This Smartphone Is Compatible With Only T-Mobile , Mint Mobile , Metro by
    T-Mobile, Tello Mobile, Ultra Mobile In The US) Xiaomi Poco C75 smartphones are
    highly compatible with carriers in Africa, the Middle East, Asia, the Caribbean,
    Latin America , UK and Europe. The POCO C75 is an entry-level smartphone
    featuring a large 6.88-inch 120Hz IPS LCD display, a 50MP rear camera, and a
    5,160mAh battery with 18W charging. It is powered by the MediaTek Helio
    G81-Ultra processor with up to 8GB RAM, running Android 14 with HyperOS. The
    device is designed for budget-conscious users, featuring a 13MP front camera and
    a side-mounted fingerprint sensor. Key Specifications:

- id: 191
  name: "Motorola Moto G ,5G , 128GB 4GB Ram , USA Version (2024) Unlocked , New."
  category: "Phones"
  description: >-
    The Motorola Moto G 5G (2024) 128GB/4GB RAM (USA Version) is a budget-friendly
    smartphone tailored specifically for North American cellular networks, offering
    essential 5G connectivity and excellent battery life. Key US
    SpecificationsNetwork Compatibility: Fully optimized for all major US carriers
    including T-Mobile, AT&T, and Verizon, supporting both nationwide 5G networks
    and standard 4G LTE.Memory &

- id: 192
  name: "Xiaomi Poco M6 Pro, 256GB, GSM Unlocked , International Version , New ,
      Sealed"
  category: "Phones"
  description: >-
    >- (This Smartphone Is Compatible With Only T-Mobile , Mint Mobile , Metro by
    T-Mobile, Tello Mobile, Ultra Mobile In The US) Xiaomi Poco M6 Pro smartphones
    are highly compatible with carriers in Africa, the Middle East, Asia, the
    Caribbean, Latin America , UK and Europe. The Poco M6 Pro 5G is a
    budget-friendly 5G smartphone featuring a 6.79-inch 90Hz FHD+ display,
    Snapdragon 4 Gen 2 chipset, and a 50MP main camera. It includes a 5,000mAh
    battery, 18W fast charging, IP53 resistance, and a 3.5mm headphone jack. It is
    available with up to 6GB RAM and 128GB storage. Key Specifications:

- id: 193
  name: "Celero , 5G , 64GB, Unlocked, New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Silver. The Celero 5G SC is an ultra-budget 5G prepaid phone
    for Boost Mobile featuring a 6.6-inch HD+ display, a 50MP main camera, and a
    5,000mAh battery. Running Android 14 with a 2.2GHz octa-core processor and 64GB
    storage, it is designed for basic tasks and includes BoostMax Audio. Key
    Specifications

- id: 194
  name: "Maxwest Neo Flip Plus , 32MB, Unlocked, New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Red , Gold , Black, Blue .The Maxwest New Flip Plus is a 4G
    LTE enabled, dual-SIM compact flip phone featuring a 2.4-inch TFT main display,
    a VGA rear camera, 32MB RAM, and 32MB internal memory (expandable via microSD).
    Designed for basic communication, it operates on a SC6531E chipset, includes a
    1400mAh battery, FM radio, and Bluetooth. Key Specifications:

- id: 195
  name: "Google Pixel 10 Pro , 128GB, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Moonstone , Obsidian , Porcelain, Jade . The Google Pixel 10
    Pro features a 6.3-inch Super Actua LTPO OLED display (1-120Hz, 3300 nits peak)
    and is powered by the Tensor G5 chip with 16GB of RAM. It includes a 50MP main,
    48MP ultrawide, and 48MP 4.5x telephoto camera, with a 4,870mAh battery,
    128GB-1TB storage, and Qi2-certified wireless charging. Key Specifications
    (Based on 2025/2026 Reports)

- id: 196
  name: "Google Pixel 10 Pro , 256GB, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Moonstone , Obsidian , Porcelain, Jade . The Google Pixel 10
    Pro features a 6.3-inch Super Actua LTPO OLED display (1-120Hz, 3300 nits peak)
    and is powered by the Tensor G5 chip with 16GB of RAM. It includes a 50MP main,
    48MP ultrawide, and 48MP 4.5x telephoto camera, with a 4,870mAh battery,
    128GB-1TB storage, and Qi2-certified wireless charging. Key Specifications
    (Based on 2025/2026 Reports)

- id: 197
  name: "Google Pixel 10 Pro , 512GB, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Moonstone , Obsidian , Porcelain, Jade . The Google Pixel 10
    Pro features a 6.3-inch Super Actua LTPO OLED display (1-120Hz, 3300 nits peak)
    and is powered by the Tensor G5 chip with 16GB of RAM. It includes a 50MP main,
    48MP ultrawide, and 48MP 4.5x telephoto camera, with a 4,870mAh battery,
    128GB-1TB storage, and Qi2-certified wireless charging. Key Specifications
    (Based on 2025/2026 Reports)

- id: 198
  name: "Google Pixel 10 Pro , 1TB Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Moonstone , Obsidian , Porcelain, Jade . The Google Pixel 10
    Pro features a 6.3-inch Super Actua LTPO OLED display (1-120Hz, 3300 nits peak)
    and is powered by the Tensor G5 chip with 16GB of RAM. It includes a 50MP main,
    48MP ultrawide, and 48MP 4.5x telephoto camera, with a 4,870mAh battery,
    128GB-1TB storage, and Qi2-certified wireless charging. Key Specifications
    (Based on 2025/2026 Reports)

- id: 199
  name: "Google Pixel 10 Pro XL, 256GB, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Moonstone, Jade, Obsidian , Porcelain. The Google Pixel 10
    Pro XL is a flagship smartphone featuring a 6.8-inch 120Hz Super Actua OLED
    display, the proprietary Google Tensor G5 chip, and 16GB of RAM. It boasts a
    5200 mAh battery with 45W wired charging, a 50MP main camera, a 48MP ultrawide
    with macro focus, and a 48MP 5x telephoto lens. Key Specifications (Based on
    early reports):

- id: 200
  name: "Google Pixel 10 Pro XL, 512GB, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Moonstone, Jade, Obsidian , Porcelain. The Google Pixel 10
    Pro XL is a flagship smartphone featuring a 6.8-inch 120Hz Super Actua OLED
    display, the proprietary Google Tensor G5 chip, and 16GB of RAM. It boasts a
    5200 mAh battery with 45W wired charging, a 50MP main camera, a 48MP ultrawide
    with macro focus, and a 48MP 5x telephoto lens. Key Specifications (Based on
    early reports):

- id: 201
  name: "Google Pixel 10 Pro XL, 1TB, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Moonstone, Jade, Obsidian , Porcelain. The Google Pixel 10
    Pro XL is a flagship smartphone featuring a 6.8-inch 120Hz Super Actua OLED
    display, the proprietary Google Tensor G5 chip, and 16GB of RAM. It boasts a
    5200 mAh battery with 45W wired charging, a 50MP main camera, a 48MP ultrawide
    with macro focus, and a 48MP 5x telephoto lens. Key Specifications (Based on
    early reports):

- id: 202
  name: "Google Pixel 10, 128GB, Unlocked , New, Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors , Obsidian ,Frost , Indigo, Lemongrass. The Google Pixel 10
    is a 6.3-inch compact flagship powered by the Tensor G5 chip, 12GB of RAM, and
    Android 16. It features a 3,000-nit peak brightness OLED display, a 48MP main
    camera, a 13MP ultrawide lens, and a new 5x telephoto zoom. Key features include
    7 years of updates, Qi2-certified 15W wireless charging, and 128GB/256GB
    storage. Core Specifications:

- id: 203
  name: "Google Pixel 10, 256GB, Unlocked , New, Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors , Obsidian ,Frost , Indigo, Lemongrass. The Google Pixel 10
    is a 6.3-inch compact flagship powered by the Tensor G5 chip, 12GB of RAM, and
    Android 16. It features a 3,000-nit peak brightness OLED display, a 48MP main
    camera, a 13MP ultrawide lens, and a new 5x telephoto zoom. Key features include
    7 years of updates, Qi2-certified 15W wireless charging, and 128GB/256GB
    storage. Core Specifications:

- id: 204
  name: "Google Pixel 9A , 128GB, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Obsidian.The Google Pixel 9a is a mid-range smartphone
    featuring the Tensor G4 chip, 8GB of RAM, and a 6.3-inch 120Hz Actua display. It
    features a large 5,100 mAh battery, 48MP main camera, and full IP68 water
    resistance, running Android 15 with 7 years of support. The design includes flat
    aluminum rails and a plastic back, available in four colors. Key Specifications

- id: 205
  name: "Google Pixel 9 ,128GB , Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Obsidian. The Google Pixel 9 is a 6.3-inch Android 14
    smartphone released in August 2024, featuring the Tensor G4 chip, 12GB of RAM,
    and a 4700 mAh battery with 24+ hour life. Priced from $799, it highlights a
    redesigned camera bar, glossy back, and advanced AI features like Gemini and
    Magic Editor. The device offers a 50MP main camera and a 48MP ultrawide lens.
    Key Features and Specifications

- id: 206
  name: "Google Pixel 9 ,256GB , Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Obsidian. The Google Pixel 9 is a 6.3-inch Android 14
    smartphone released in August 2024, featuring the Tensor G4 chip, 12GB of RAM,
    and a 4700 mAh battery with 24+ hour life.,8highlights a redesigned camera bar,
    glossy back, and advanced AI features like Gemini and Magic Editor. The device
    offers a 50MP main camera and a 48MP ultrawide lens. Key Features and
    Specifications

- id: 207
  name: "Google pixel 9 Pro Fold , 256GB, Unlocked ,New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Obsidian , Porcelain. The Goigle 9 Pro Fold (2024) is a
    premium foldable featuring an 8-inch Super Actua Flex (LTPO) internal display
    (2076 x 2152, 1-120Hz) and a 6.3-inch OLED external screen. Powered by the
    Tensor G4 chip and 16GB RAM, it features a 48MP main camera, 10.5MP ultrawide,
    and 10.8MP 5x telephoto camera, reaching up to 2,700 nits peak brightness. Key
    Specifications

- id: 208
  name: "Google pixel 9 Pro Fold , 512GB, Unlocked ,New , Sealed"
  category: "Phones"
  description: >-
    >- Available Colors Obsidian. The Goigle 9 Pro Fold (2024) is a premium foldable
    featuring an 8-inch Super Actua Flex (LTPO) internal display (2076 x 2152,
    1-120Hz) and a 6.3-inch OLED external screen. Powered by the Tensor G4 chip and
    16GB RAM, it features a 48MP main camera, 10.5MP ultrawide, and 10.8MP 5x
    telephoto camera, reaching up to 2,700 nits peak brightness. Key Specifications

- id: 209
  name: "Google Pixel 9 Pro XL , 128GB, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Obsidian, Hazel, Rose Quartz , Porcelain. The Google Pixel 9
    Pro XL is a flagship smartphone featuring a 6.8-inch Super Actua LTPO OLED
    display (1344 x 2992, 120Hz), Tensor G4 processor, and 16GB of RAM. It offers a
    50MP main/48MP ultra-wide/48MP 5x telephoto camera system with a 42MP front
    camera, 5060 mAh battery, and 7 years of software support. Key Specifications

- id: 210
  name: "Google Pixel 9 Pro XL , 256GB, Unlocked , New , Sealed"
  category: "Phones"
  description: >-
    >- Avaiable Colors Obsidian, Hazel, Rose Quartz , Porcelain. The Google Pixel 9
    Pro XL is a flagship smartphone featuring a 6.8-inch Super Actua LTPO OLED
    display (1344 x 2992, 120Hz), Tensor G4 processor, and 16GB of RAM. It offers a
    50MP main/48MP ultra-wide/48MP 5x telephoto camera system with a 42MP front
    camera, 5060 mAh battery, and 7 years of software support. Key Specifications

