products:
- id: 121
  name: "Apple iPhone SE 2020 ,128GB , Physical SIM , Unlocked , A- Grade,"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) Handset Only. The iPhone SE (2020) packed flagship
    power into an iPhone 8 body, featuring the A13 Bionic chip, a 4.7-inch Retina HD
    display, a 12MP Wide rear camera, and Touch ID in the Home button, with storage
    options up to 256GB. It offered IP67 water resistance and wireless charging,
    running iOS. Key specs include 3GB RAM, stereo speakers, and a 7MP front camera,
    with no headphone jack, making it a compact device with powerful performance for
    its time . Display

- id: 122
  name: "Apple iPhone XR , 64GB , Unlocked  Physical SIM , A-Grade , Certified
      Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) Handset Only. The iPhone XR, released in 2018, was
    a popular, more affordable version of the iPhone X, featuring an all-screen
    design with a 6.1-inch LCD (Liquid Retina) display, the A12 Bionic chip, Face
    ID, and a single 12MP wide rear camera, notable for its diverse color options
    and good battery life. While lacking some features of the higher-end XS (like
    OLED and a second camera lens), it offered solid performance and became a
    bestseller, still receiving iOS updates in 2025 but with a design showing its
    age compared to newer models. Key Features:

- id: 123
  name: "Apple iPhone 11, 64GB , Physical SIM , Unlocked , A+ Grade, Certified"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The iPhone 11 features a 6.1-inch Liquid Retina HD
    display, the A13 Bionic chip, and a dual 12MP Wide/Ultra Wide rear camera system
    with Night Mode, plus a 12MP front camera, offering long battery life and water
    resistance with Face ID for security, running iOS. It supports Gigabit-class
    LTE, Wi-Fi 6, and Bluetooth 5.0, with storage options up to 256GB, and includes
    features like Spatial Audio and Cinematic Mode for video. Display & Design

- id: 124
  name: "Apple 11 Pro Max , 256GB , Physical SIM , Unlocked , A- Grade , Certified"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) Details Handset Only. The iPhone 11 Pro Max
    features a large 6.5-inch Super Retina XDR (OLED) display, powered by the A13
    Bionic chip, with a triple 12MP camera system (Ultra Wide, Wide, Telephoto) and
    4GB RAM, offering storage up to 512GB, IP68 water resistance, Face ID, wireless
    charging, and support for Gigabit LTE (no 5G), running iOS.

- id: 125
  name: "Apple 11 Pro Max , 64GB, Physical SIM , Unlocked , A- Grade , Certified"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) Handset Only. The iPhone 11 Pro Max features a
    large 6.5-inch Super Retina XDR (OLED) display, powered by the A13 Bionic chip,
    with a triple 12MP camera system (Ultra Wide, Wide, Telephoto) and 4GB RAM,
    offering storage up to 512GB, IP68 water resistance, Face ID, wireless charging,
    and support for Gigabit LTE (no 5G), running iOaS.

- id: 126
  name: "Apple iPhone 12 Pro Max, 256GB, Physical SIM, Unlocked, A- Grade ,"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) Handset Only. The iPhone 12 Pro Max features a
    large 6.7-inch Super Retina XDR (OLED) display, the A14 Bionic chip, a Pro 12MP
    Triple Camera System (Ultra Wide, Wide, Telephoto) with LiDAR, and a durable
    stainless steel design with Ceramic Shield. Key specs include 6GB RAM, 5G
    connectivity, MagSafe, 128/256/512GB storage, and support for up to iOS 26.2,
    offering strong performance and camera capabilities for its time, though lacking
    a high refresh rate. Display & Design

- id: 127
  name: "Apple iPhone 12 Pro Max , 128GB , Physical SIM , Unlocked , A- Grade ,"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) Handset Only. The iPhone 12 Pro Max features a
    large 6.7-inch Super Retina XDR (OLED) display, the A14 Bionic chip, a Pro 12MP
    Triple Camera System (Ultra Wide, Wide, Telephoto) with LiDAR, and a durable
    stainless steel design with Ceramic Shield. Key specs include 6GB RAM, 5G
    connectivity, MagSafe, 128/256/512GB storage, and support for up to iOS 26.2,
    offering strong performance and camera capabilities for its time, though lacking
    a high refresh rate. Display & Design

- id: 128
  name: "Apple iPhone 12 Mini , 128GB , Physical SIM , Unlocked , A- Grade ,
      Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The iPhone 12 mini is a compact 5.4-inch 5G
    smartphone featuring an OLED Super Retina XDR display, A14 Bionic chip, and
    Ceramic Shield front cover. It has a 12MP dual-camera system (wide/ultra-wide),
    4GB RAM, and 64GB/128GB/256GB storage options. Key specs include IP68 water
    resistance, Face ID, and a 2,227mAh battery. Key Technical Specifications

- id: 129
  name: "Apple iPhone 12 , 64GB , Physical SIM , Unlocked , A- Grade , Certified"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The Apple iPhone 12 features a 6.1-inch Super
    Retina XDR OLED display, A14 Bionic chip, 5G connectivity, and a Ceramic Shield
    front cover. It includes a dual 12MP camera system, MagSafe charging, IP68 water
    resistance, and 4GB of RAM with 64GB, 128GB, or 256GB storage options. Key
    Specifications:

- id: 130
  name: "Apple iPhone 13 Mini , 256GB , Physical SIM , Unlocked , A-  Grade  ,"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The iPhone 13 mini (2021) is a compact flagship
    featuring a 5.4-inch Super Retina XDR OLED display, A15 Bionic chip, and
    improved dual 12MP cameras (wide/ultra-wide) with Sensor-Shift OIS. Key specs
    include 4GB RAM, 128GB-512GB storage, Face ID, 5G connectivity, and a ~2438mAh
    battery with MagSafe. It measures 5.18×2.53×0.305.18 cross 2.53 cross 0.30
    5.18×2.53×0.30 inches and weighs 141 grams. Key Specifications

- id: 131
  name: "Apple iPhone XS , 64GB , Physical SIM , Unlocked , A- Grade , Certified"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) Handset Only. The iPhone XS (released 2018)
    features a 5.8-inch Super Retina OLED display (2436x1125), A12 Bionic chip, 4GB
    RAM, and a dual 12MP rear camera system (wide/telephoto) with 4K video. It
    includes Face ID, IP68 water resistance, and a 2,658mAh battery. Available in
    64GB, 256GB, or 512GB storage, it supports Gigabit LTE, NFC, and wireless
    charging. Key Specifications:

- id: 132
  name: "Apple iPhone XS Max , 256GB , Physical SIM , Unlocked , A- Grade ,"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) Handset Only The Apple iPhone XS Max features a
    6.5-inch Super Retina OLED display (2688 x 1242), A12 Bionic chip, 4GB RAM, and
    a 3,174 mAh battery. Key specs include dual 12MP rear cameras (wide/telephoto),
    IP68 water resistance, Face ID, and storage options of 64GB, 256GB, or 512GB.
    Released in 2018, it supports iOS 18. Key Technical Specifications

- id: 133
  name: "Apple iPhone XS Max , 64GB , Physical SIM , Unlocked , A- Grade ,"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) Handset Only The Apple iPhone XS Max features a
    6.5-inch Super Retina OLED display (2688 x 1242), A12 Bionic chip, 4GB RAM, and
    a 3,174 mAh battery. Key specs include dual 12MP rear cameras (wide/telephoto),
    IP68 water resistance, Face ID, and storage options of 64GB, 256GB, or 512GB.
    Released in 2018, it supports iOS 18. Key Technical Specifications

- id: 134
  name: "Apple iPhone 7, 32GB , Physical SIM , Unlocked , A-Grade , Certified
      Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) Handset Only The iPhone 7 (2016) features a
    4.7-inch Retina HD display, Apple A10 Fusion chip, 2GB RAM, and 12MP rear camera
    with 4K video. It has an IP67 water-resistant rating, Touch ID, and a 1,960mAh
    battery. It was released with iOS 10 and is upgradable to iOS 15. Key
    Specifications:

- id: 135
  name: "Google 8 Pro 128GB, Unlocked , A-Grade , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The Google Pixel 8 Pro features a 6.7-inch Super
    Actua LTPO OLED display (1-120Hz), the Google Tensor G3 chip, 12GB RAM, and a
    5050mAh battery. It boasts a powerful triple rear camera system (50MP main, 48MP
    ultrawide, 48MP telephoto) with advanced AI photo/video tools like Video Boost
    and Best Take. Key Specifications

- id: 136
  name: "Google Pixel 8 Pro, 256GB, Unlocked, A-Grade , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) TheGoogle Pixel 8 Pro features a 6.7-inch Super
    Actua LTPO OLED display (1-120Hz), the Google Tensor G3 chip, 12GB RAM, and a
    5050mAh battery. It boasts a powerful triple rear camera system (50MP main, 48MP
    ultrawide, 48MP telephoto) with advanced AI photo/video tools like Video Boost
    and Best Take. Key Specifications

- id: 137
  name: "Google Pixel 8, 128GB, A-Grade, Unlocked , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The Google Pixel 8 is a compact 6.2-inch flagship
    smartphone featuring the Tensor G3 chip, 8GB RAM, a 120Hz Actua OLED display,
    and a 50MP main camera. Key specs include a 4575mAh battery, 27W wired charging,
    and 7 years of Android OS/security updates. It offers premium features like IP68
    water resistance, Face/Fingerprint Unlock, and AI-driven camera tools. Key
    Specifications

- id: 138
  name: "Google Pixel 7A, 128GB, Unlocked , A-Grade , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The Google Pixel 7a features a 6.1-inch FHD+ OLED
    90Hz display, powered by the Google Tensor G2 chip, with 8GB RAM and 128GB
    storage, a 64MP main camera, 13MP ultrawide, 13MP selfie camera, and a 4385mAh
    battery with wireless charging, all running Android. Display

- id: 139
  name: "Google Pixel 7,128GB, A-Grade, Unlocked , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The Google Pixel 7 features a 6.3-inch OLED display
    (90Hz) with Corning Gorilla Glass Victus, powered by the Google Tensor G2
    processor, 8GB of RAM, and a 4355mAh battery. It includes a 50MP main camera, a
    12MP ultrawide camera, and 128GB or 256GB of storage. It runs on Android 13,
    features an IP68 rating, and is known for AI-powered camera features like Magic
    Eraser and Photo Unblur. Key Specifications for Google Pixel 7:

- id: 140
  name: "Google Pixel 7 Pro ,128GB, Unlocked, A-Grade , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The Google Pixel 7 Pro features a 6.7-inch QHD+
    LTPO OLED display (120Hz), the Google Tensor G2 chipset with 12GB RAM, and a
    5,000mAh battery. Its triple rear camera system includes a 50MP main, 48MP 5x
    telephoto, and 12MP ultrawide lens, supporting up to 30x Super Res Zoom. It runs
    Android 13 (upgradable) and features IP68 water resistance, Face/Fingerprint
    unlock, and 128GB/256GB/512GB storage options. Key Specifications:

- id: 141
  name: "Google Pixel 7 Pro ,256GB, Unlocked, A-Grade , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty)The Google Pixel 7 Pro features a 6.7-inch QHD+ LTPO
    OLED display (120Hz), the Google Tensor G2 chipset with 12GB RAM, and a 5,000mAh
    battery. Its triple rear camera system includes a 50MP main, 48MP 5x telephoto,
    and 12MP ultrawide lens, supporting up to 30x Super Res Zoom. It runs Android 13
    (upgradable) and features IP68 water resistance, Face/Fingerprint unlock, and
    128GB/256GB/512GB storage options. Key Specifications:

- id: 142
  name: "Google Pixel 7 Pro 512GB, Unlocked, A-Grade , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The Google Pixel 7 Pro features a 6.7-inch QHD+
    LTPO OLED display (120Hz), the Google Tensor G2 chipset with 12GB RAM, and a
    5,000mAh battery. Its triple rear camera system includes a 50MP main, 48MP 5x
    telephoto, and 12MP ultrawide lens, supporting up to 30x Super Res Zoom. It runs
    Android 13 (upgradable) and features IP68 water resistance, Face/Fingerprint
    unlock, and 128GB/256GB/512GB storage options. Key Specifications:

- id: 143
  name: "Google Pixel 9 Pro, 128GB, Unlocked, A-2 Grade , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The Google Pixel 9 Pro is a compact flagship,
    featuring a 6.3-inch Super Actua LTPO OLED display (1-120Hz, up to 3000 nits
    peak), Tensor G4 processor, 16GB RAM, and a 4700mAh battery. It boasts a
    triple-rear camera system (50MP wide, 48MP ultrawide, 48MP 5x telephoto) and a
    42MP front camera. Key features include 27W wired charging, Android 14, and
    128GB to 1TB storage. Key Specifications

- id: 144
  name: "Samsung Galaxy A52 , 128GB ,Unlocked , A+Grade , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The Samsung Galaxy A52 (released 2021) is a
    mid-range smartphone featuring a 6.5-inch Super AMOLED 90Hz/120Hz display,
    Snapdragon 720G/750G processor, and a 64MP main camera with OIS. Known for its
    IP67 water resistance, 4,500mAh battery with 25W charging, and expandable
    storage, it offers a solid, durable package. It supports up to Android 14 and is
    considered a capable, budget-friendly device. Key Specifications and Features

- id: 145
  name: "Samsung Galaxy A54 , 128GB , Unlocked , A+ Grade , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The Samsung Galaxy A54 5G features a 6.4-inch 120Hz
    FHD+ Super AMOLED display, Exynos 1380 processr, 50MP OIS main camera, and a
    5000mAh battery with 25W charging. Released in 2023, it includes IP67 water
    resistance, 6GB/8GB RAM, and 128GB/256GB storage, expandable up to 1TB via
    microSD. Key Specifications

- id: 146
  name: "Samsung Galaxy S21 Ultra,128GB, Unlocked, A+Grade , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The Samsung Galaxy S21 Ultra 5G features a 6.8-inch
    Dynamic AMOLED 2X display with a 120Hz adaptive refresh rate, powered by a
    Snapdragon 888 or Exynos 2100 processor. It includes a 108MP quad-camera system
    with 100x Space Zoom, a 5000mAh battery, and supports S Pen functionality,
    running on Android 11 up to 4 major upgrades. This video provides a detailed
    overview of the Galaxy S21 Ultra's specifications: Core Specifications:

- id: 147
  name: "Samsung Galaxy S23 Ultra, 256GB, Unlocked, A+Grade , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    > (90-Day Limited Warranty) The Samsung Galaxy S23 Ultra is a premium 5G
    smartphone featuring a 6.8-inch QHD+ Dynamic AMOLED 2X display (1-120Hz), a
    200MP main camera, and a built-in S Pen. Powered by the Snapdragon 8 Gen 2 for
    Galaxy chipset, it includes a 5,000mAh battery with 45W fast charging, up to
    12GB of RAM, and 1TB of storage. This video provides a detailed review of the
    Samsung Galaxy S23 Ultra's features and performance. Key Specifications

- id: 148
  name: "Samsung Galaxy Note 20, 128GB, Unlocked, A+Grade , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    >- (90-Day Limited Warranty) The Samsung Galaxy Note 20 5G (2020) features a
    6.7-inch Super AMOLED+ 60Hz display, Snapdragon 865+ or Exynos 990 processor,
    8GB RAM, and a 4300mAh battery. It boasts a 12MP wide, 64MP telephoto (3x
    optical/30x space zoom), and 12MP ultra-wide triple camera system with 8K video
    recording. Key Specifications:

- id: 149
  name: "AT&T Radiant Max , 32GB ,4G , Unlocked , A+Grade , Certified Pre-owned"
  category: "Pre-Owned Phones & Tablets"
  description: >-
    (90-Day Limited Warranty) The official hardware specifications for the AT&T
    Radiant Max (4G LTE) and the upgraded AT&T Radiant Max 5G detail the exact
    capabilities of each device. According to the official AT&T Device Support
    Documentation, the standalone hardware specifications are itemized below:AT&T
    Radiant Max (4G LTE Model)Display: 6.5-inch HD+ LCD (1560 x 720 resolution),
    protected by Corning Gorilla Glass 5.Processor: 2.0 GHz Octa-Core MediaTek Helio
    P22.Storage: 32GB internal storage, expandable up to 128GB via microSD card.RAM:
    3GB RAM.Rear Camera: Triple setup—13MP (main) + 5MP (ultra-wide) + 2MP (depth
    sensor).Front Camera: 8MP front-facing selfie camera.Battery: 4,000 mAh internal
    battery (Up to 2 days of battery life; fast-charging via USB-C).Operating
    System: Android 10.Security & Features: Rear fingerprint sensor, 3.5mm headphone
    jack, and DTS audio enhancement.AT&T Radiant Max 5G (Upgraded Model)Display:
    6.82-inch HD+ LCD scratch-resistant display.Processor: MediaTek Dimensity 700
    Octa-Core chipset.Storage: 64GB internal storage, expandable up to 512GB via
    microSD card.RAM: 4GB RAM.Rear Camera: Quad AI setup—48MP (main) + 8MP
    (ultra-wide) + 2MP (macro) + 2MP (portrait depth).Front Camera: 13MP
    front-facing selfie camera.Battery: 4,750 mAh internal battery supporting both
    standard fast-charging and wireless charging capabilities.Operating

